openapi: 3.0.0
info: 
    title: "Events"
    description: "API for events. Fetching all events, fetching unique event by id and searching for event by title. Updating picture and description for an event."
    version: "1.0.0"
schemes:
- "http"
- "https"

paths: 
    /Event:
        description: All Tickets
        get:
          description: Operation to Fetch All Tickets
          operationId: findAllEvents
          responses:
            200:
              description: Successful Response
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      eventID:
                        type: integer
                      title:
                        type: string
                      description:
                        type: string
                      price:
                        type: integer
                      startTime:
                        type: string
                        format: date-time
                      location:
                        type: string
                      numTick:
                        type: integer
                      eventPictureLink:
                        type: array
                        items:
                          type: string
                    example:
                      - eventID: 1
                        title: Queen Concert
                        description: A concert by Queen.
                        price: 500
                        startTime: 2023-07-21T17:32:28Z
                        location: Friends Arena Stockholm
                        numTick: 5
                        eventPictureLink: pictureUrl1
                      - eventID: 2
                        title: Rolling Stones Concert
                        description: A concert by Rolling Stones.
                        price: 400
                        startTime: 2023-10-21T17:32:28Z
                        location: Ullevi Göteborg
                        numTick: 4
                        eventPictureLink: pictureUrl2
            400:
              description: Invalid Response

 /Event/{eventID}:
        description: Reach single event by ID
        get:
          description: Fetch single event by ID
          operationId: findUniqueEvent
          parameters:
          - in: path
            name: eventID
            description: ID of event that needs to be fetched
            required: true
            schema:
              type: integer
          responses:
            200:
              description: Successful Response
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      eventID:
                        type: integer
                      title:
                        type: string
                      description:
                        type: string
                      price:
                        type: integer
                      startTime:
                        type: string
                        format: date-time
                      location:
                        type: string
                      numTick:
                        type: integer
                      eventPictureLink:
                        type: array
                        items:
                          type: string
                  example:
                      - eventID: 1
                        title: Queen Concert
                        description: A concert by Queen.
                        price: 500
                        startTime: 2023-07-21T17:32:28Z
                        location: Friends Arena Stockholm
                        numTick: 5
                        eventPictureLink: pictureUrl1
            400:
              description: Invalid Response
        put:
          description: Updates a unique event with description or image
          operationId: updateUniqueEvent
          parameters:
          - in: path
            name: eventID
            description: ID of event that needs to be fetched
            required: true
            schema:
              type: integer
          responses:
            200:
              description: Successful Operation
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      eventID:
                        type: integer
                      title:
                        type: string
                      description:
                        type: string
                      price:
                        type: integer
                      startTime:
                        type: string
                        format: date-time
                      location:
                        type: string
                      numTick:
                        type: integer
                      eventPictureLink:
                        type: array
                        items:
                          type: string
                  example:
                      - eventID: 1
                        title: Queen Concert
                        description: A concert by Queen again.
                        price: 500
                        startTime: 2023-07-21T17:32:28Z
                        location: Friends Arena Stockholm
                        numTick: 5
                        eventPictureLink: pictureUrl3
            400:
              description: Invalid Operation
