version: "3"
services:
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    build: ./server
    ports:
      - 7050:7050
    volumes:
      - "./server:/app"
      - "/app/node_modules"

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pvk_db_dummy
    volumes:
      - "./database/pgdata:/var/lib/postgresql/data"
      - "./database/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql"
      - "./database/dummydata.sql:/docker-entrypoint-initdb.d/02_dummydata.sql"
    ports:
      - "5432:5432"
