openapi: 3.0.0
info:
  title: Biljettsystem (MVP)
  description: This is an API specification for event information is ticket. Should include Buying any number of tickets for an event, and getting ticket information.
  version: 1.0.0
  

paths:
  /tickets:
    description: All Available Tickets
    get:
      description: Operation to Fetch All Tickets
      responses:
        200:
          description: Success Response
          content: 
            application/json:
              schema:
                type: object
                properties:
                  ticketID:
                    type: integer
                  price:
                    type: integer
                  eventID:
                    type: integer
                  purchased:
                    type: boolean
                example:
                  - ticketID: 1
                    price: 899
                    eventID: 1
                    purchased: false
                  - ticketID: 2
                    price: 899
                    eventID: 1
                    purchased: true
                  - ticketID: 3
                    price: 1099
                    eventID: 2
                    purchased: false
  /tickets/{eventID}:
    description: Single Event Ticket Resource
    get:
      description: Operation to Fetch All Tickets for Single Event
      parameters:
        - in: path
          name: eventID
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ticketID:
                    type: integer
                  price:
                    type: integer
                  eventID:
                    type: integer
                example:
                  - ticketID: 1
                    price: 899
                    eventID: 1
                    purchased: false
                  - ticketID: 2
                    price: 899
                    eventID: 1
                    purchased: true
    post:
      description: Book a ticket
      parameters:
        - in: path
          name: eventID
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                eventID:
                  type: integer
                email:
                  type: string
              example:
                - eventID: 1
                  email: 'abc@gmail.com'
      responses:
        201:
          description: Ticket has been reserved!
          
  /tickets/{ticketID}:
    description: Single Ticket Resource
    get:
      description: Operation to Fetch Single Ticket from Single Event
      parameters:
        - in: path
          name: ticketID
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ticketID:
                    type: integer
                  price:
                    type: integer
                  eventID:
                    type: integer
                example:
                  - ticketID: 2
                    price: 899
                    eventID: 1
                    purchased: true
          
                  
               
 
      
