DROP TABLE IF EXISTS Event CASCADE;
DROP TABLE IF EXISTS Category CASCADE;
DROP TABLE IF EXISTS EventCategories CASCADE;
DROP TABLE IF EXISTS User CASCADE;
DROP TABLE IF EXISTS Purchase CASCADE;
DROP TABLE IF EXISTS Ticket CASCADE;

CREATE TABLE Event (
    EventID SERIAL PRIMARY KEY,
    Name varchar(255) NOT NULL,
    Description text,
    Price double precision NOT NULL,
    StartTime timestamp NOT NULL,
    Location varchar(255) NOT NULL,
    NumTick int NOT NULL,
    EventPictureLink varchar(255)
);

CREATE TABLE Category (
    CategoryID SERIAL PRIMARY KEY,
    Name varchar(255) NOT NULL
);

CREATE TABLE EventCategories (
    EventID int REFERENCES Event(EventID) PRIMARY KEY ON UPDATE CASCADE ON DELETE CASCADE,
    CategoryID int REFERENCES Category(CategoryID) PRIMARY KEY ON UPDATE CASCADE ON DELETE CASCADE,
);

CREATE TABLE User (
    UserID SERIAL PRIMARY KEY,
    Name varchar(255),
    Mail varchar(255) NOT NULL
);

CREATE TABLE Purchase (
    PurchaseID SERIAL PRIMARY KEY,
    EventID int REFERENCES Event(EventID) NOT NULL ON UPDATE CASCADE ON DELETE CASCADE,
    UserID int REFERENCES User(UserID) NOT NULL ON UPDATE CASCADE ON DELETE CASCADE,
    PurchaseTime timestamp NOT NULL
);

CREATE TABLE Ticket (
    TicketID SERIAL PRIMARY KEY,
    PurchaseID int REFERENCES Purchase(PurchaseID) NOT NULL ON UPDATE CASCADE ON DELETE CASCADE
);
